In [7]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib ipympl

# Echauffement : le broadcasting
print('questions concernant a')

a = np.array([1, 2, 3])
# 1. visualisation de l'action du None
print(a, a.shape)
print(a[:, None], a[:, None].shape)
print(a[None, :], a[None, :].shape)

# 2. forme du tableau X : (3,3) ; X[i,j]=i-j
X=a[:, None]-a[None, :]
print(X, X.shape)

# 3. 
print('questions concernant b')
# forme de b[:, None, :] -> (2,1,3)
# forme de b[:, :, None] -> (2,3,1)
# donc forme du tableau calculé : (2,3,3)
b=np.array([[1,2,3],[4,5,6]])
print(b, b.shape)
Y= b[:, None, :] - b[:, :, None]
print(Y,Y.shape)

questions concernant a
[1 2 3] (3,)
[[1]
 [2]
 [3]] (3, 1)
[[1 2 3]] (1, 3)
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]] (3, 3)
questions concernant b
[[1 2 3]
 [4 5 6]] (2, 3)
[[[ 0  1  2]
  [-1  0  1]
  [-2 -1  0]]

 [[ 0  1  2]
  [-1  0  1]
  [-2 -1  0]]] (2, 3, 3)


In [ ]:
# Initialisation aléatoire
# les bornes pour le tirage au sort initial
mass_max = 3.
    
x_min, x_max = -10., 10.
y_min, y_max = -10., 10.

speed_max = 1.

# votre code

def init_problem(N):
    """
    retourne un tuple masses, positions, speeds
    de formes resp.   (N,)    (2, N)     (2, N)
    tiré au sort dans les bornes définies ci-dessus
    """
    masses=np.random.uniform(0,mass_max,(N,))

    positionsx, positionsy =  np.random.uniform(x_min,x_max,(N,)), np.random.uniform(y_min,y_max,(N,))
    positionsx, positionsy = positionsx[None, :], positionsy[None, :] # empaquetage de chaque ligne pour avoir 2 lignes différentes lors de la concaténation
    positions = np.concatenate((positionsx, positionsy), axis=0)

    speedsx, speedsy =  np.random.uniform(0,speed_max,(N,)), np.random.uniform(0,speed_max,(N,))
    speedsx, speedsy=speedsx[None, :], speedsy[None, :]
    speeds = np.concatenate((speedsx, speedsy), axis=0)
    
    return masses, positions, speeds

# pour tester

# normalement vous devez pouvoir faire ceci

masses, positions, speeds = init_problem(10)

#print(masses, masses.shape)
#print(positions, positions.shape)
#print(speeds, speeds.shape)

# et ceci devrait afficher OK
try:
    assert masses.shape == (10,) and positions.shape == speeds.shape == (2, 10)
    print("OK")
except:
    print("KO")

[2.76311288 2.34568548 2.18098956 0.94590384 1.63382474 2.01363926
 1.81957417 2.89786253 1.95267068 1.9712495 ] (10,)
[[ 5.17091684 -8.4053363  -7.18034587 -8.31565117  3.11922746 -3.96744211
   6.18888338 -2.33649922  5.79811286  1.91341262]
 [ 4.24798955  2.02190671 -3.44155386 -5.64579869  4.10696703  8.8165398
  -7.94708582 -5.45026905 -3.46264362  5.98561422]] (2, 10)
[[0.19292861 0.69222742 0.63890447 0.62261137 0.07273232 0.7720503
  0.75938626 0.9857686  0.18298974 0.31233813]
 [0.88593452 0.85374635 0.80784591 0.35644495 0.18012852 0.42009969
  0.19422797 0.77014707 0.9611333  0.65579368]] (2, 10)
OK


In [ ]:
# Initialisation reproductible